#!/bin/bash

# Hytale Test Server Start Script
# Generated by Rubidium setupserver.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "Starting Hytale Test Server..."
echo "Press Ctrl+C to stop"
echo ""

# Check for assets
ASSETS_ARG=""
if [ -d "assets" ] && [ "$(ls -A assets 2>/dev/null)" ]; then
    ASSETS_ARG="--assets assets"
fi

# Start server with recommended JVM flags
java \
    -Xms1G \
    -Xmx4G \
    -XX:+UseG1GC \
    -XX:+ParallelRefProcEnabled \
    -XX:MaxGCPauseMillis=200 \
    -XX:+UnlockExperimentalVMOptions \
    -XX:+DisableExplicitGC \
    -XX:+AlwaysPreTouch \
    -XX:G1NewSizePercent=30 \
    -XX:G1MaxNewSizePercent=40 \
    -XX:G1HeapRegionSize=8M \
    -XX:G1ReservePercent=20 \
    -XX:G1HeapWastePercent=5 \
    -XX:G1MixedGCCountTarget=4 \
    -XX:InitiatingHeapOccupancyPercent=15 \
    -XX:G1MixedGCLiveThresholdPercent=90 \
    -XX:G1RSetUpdatingPauseTimePercent=5 \
    -XX:SurvivorRatio=32 \
    -XX:+PerfDisableSharedMem \
    -XX:MaxTenuringThreshold=1 \
    -Dfile.encoding=UTF-8 \
    --add-opens java.base/java.lang=ALL-UNNAMED \
    --add-opens java.base/java.util=ALL-UNNAMED \
    -jar HytaleServer.jar \
    --bind 0.0.0.0:5520 \
    --auth-mode offline \
    --accept-early-plugins \
    $ASSETS_ARG \
    "$@"
