#!/bin/bash

# Rubidium Framework - Test Server Setup Script
# This script automatically sets up a local Hytale test server with Rubidium

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVER_DIR="$SCRIPT_DIR/test-server"
PLUGINS_DIR="$SERVER_DIR/earlyplugins"
ASSETS_DIR="$SERVER_DIR/assets"

echo "=========================================="
echo "  Rubidium Test Server Setup"
echo "=========================================="
echo ""

# Check for Java 25
echo "[1/6] Checking Java version..."
if command -v java &> /dev/null; then
    JAVA_VERSION=$(java -version 2>&1 | head -n 1 | cut -d'"' -f2 | cut -d'.' -f1)
    if [ "$JAVA_VERSION" -ge 25 ] 2>/dev/null; then
        echo "  ✓ Java $JAVA_VERSION detected"
    else
        echo "  ⚠ Java 25+ recommended (found Java $JAVA_VERSION)"
    fi
else
    echo "  ✗ Java not found! Please install Java 25+"
    exit 1
fi

# Create server directory structure
echo "[2/6] Creating server directories..."
mkdir -p "$SERVER_DIR"
mkdir -p "$PLUGINS_DIR"
mkdir -p "$ASSETS_DIR"
mkdir -p "$SERVER_DIR/worlds"
mkdir -p "$SERVER_DIR/logs"
mkdir -p "$SERVER_DIR/config"
echo "  ✓ Directories created"

# Copy HytaleServer.jar
echo "[3/6] Setting up HytaleServer.jar..."
if [ -f "$SCRIPT_DIR/libs/HytaleServer.jar" ]; then
    cp "$SCRIPT_DIR/libs/HytaleServer.jar" "$SERVER_DIR/HytaleServer.jar"
    echo "  ✓ HytaleServer.jar copied from libs/"
elif [ -f "$SCRIPT_DIR/../attached_assets/HytaleServer_1768383316358.jar" ]; then
    cp "$SCRIPT_DIR/../attached_assets/HytaleServer_1768383316358.jar" "$SERVER_DIR/HytaleServer.jar"
    echo "  ✓ HytaleServer.jar copied from attached_assets/"
else
    echo "  ✗ HytaleServer.jar not found!"
    echo "    Please place HytaleServer.jar in libs/ folder"
    exit 1
fi

# Build Rubidium
echo "[4/6] Building Rubidium Framework (Plus Edition)..."
cd "$SCRIPT_DIR"
if ./gradlew rubidiumPlusJar --quiet 2>/dev/null; then
    echo "  ✓ Rubidium Plus built successfully"
else
    echo "  ⚠ Build had warnings (continuing...)"
fi

# Copy Rubidium to plugins
echo "[5/6] Installing Rubidium plugin..."
if [ -f "$SCRIPT_DIR/build/libs/rubidium_plus.jar" ]; then
    rm -f "$PLUGINS_DIR/Rubidium-*.jar" "$PLUGINS_DIR/rubidium*.jar" 2>/dev/null
    cp "$SCRIPT_DIR/build/libs/rubidium_plus.jar" "$PLUGINS_DIR/"
    echo "  ✓ rubidium_plus.jar installed to earlyplugins/"
else
    echo "  ✗ Rubidium JAR not found in build/libs/"
    exit 1
fi

# Create server config
echo "[6/6] Creating server configuration..."
cat > "$SERVER_DIR/config/server.properties" << 'EOF'
# Hytale Server Configuration
# Generated by Rubidium setupserver.sh

server-name=Rubidium Test Server
server-port=5520
max-players=20
view-distance=8
auth-mode=offline
enable-command-block=true
spawn-protection=0
allow-flight=true
pvp=true
difficulty=normal
gamemode=survival
EOF
echo "  ✓ Server configuration created"

# Create run script
cat > "$SERVER_DIR/start.sh" << 'EOF'
#!/bin/bash

# Hytale Test Server Start Script
# Generated by Rubidium setupserver.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "Starting Hytale Test Server..."
echo "Press Ctrl+C to stop"
echo ""

# Check for assets
ASSETS_ARG=""
if [ -d "assets" ] && [ "$(ls -A assets 2>/dev/null)" ]; then
    ASSETS_ARG="--assets assets"
fi

# Start server with recommended JVM flags
java \
    -Xms1G \
    -Xmx4G \
    -XX:+UseG1GC \
    -XX:+ParallelRefProcEnabled \
    -XX:MaxGCPauseMillis=200 \
    -XX:+UnlockExperimentalVMOptions \
    -XX:+DisableExplicitGC \
    -XX:+AlwaysPreTouch \
    -XX:G1NewSizePercent=30 \
    -XX:G1MaxNewSizePercent=40 \
    -XX:G1HeapRegionSize=8M \
    -XX:G1ReservePercent=20 \
    -XX:G1HeapWastePercent=5 \
    -XX:G1MixedGCCountTarget=4 \
    -XX:InitiatingHeapOccupancyPercent=15 \
    -XX:G1MixedGCLiveThresholdPercent=90 \
    -XX:G1RSetUpdatingPauseTimePercent=5 \
    -XX:SurvivorRatio=32 \
    -XX:+PerfDisableSharedMem \
    -XX:MaxTenuringThreshold=1 \
    -Dfile.encoding=UTF-8 \
    --add-opens java.base/java.lang=ALL-UNNAMED \
    --add-opens java.base/java.util=ALL-UNNAMED \
    -jar HytaleServer.jar \
    --bind 0.0.0.0:5520 \
    --auth-mode offline \
    --accept-early-plugins \
    $ASSETS_ARG \
    "$@"
EOF
chmod +x "$SERVER_DIR/start.sh"

# Create stop script  
cat > "$SERVER_DIR/stop.sh" << 'EOF'
#!/bin/bash
echo "Stopping Hytale server..."
pkill -f "HytaleServer.jar" || echo "Server not running"
EOF
chmod +x "$SERVER_DIR/stop.sh"

echo ""
echo "=========================================="
echo "  Setup Complete!"
echo "=========================================="
echo ""
echo "Server location: $SERVER_DIR"
echo ""
echo "To start the server:"
echo "  cd test-server && ./start.sh"
echo ""
echo "To install your plugins:"
echo "  Copy JAR files to: $PLUGINS_DIR"
echo ""
echo "Server will run on: localhost:5520 (UDP)"
echo ""
echo "Happy modding!"
